version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    build: .
    # image: nosnibor89/sailsjs:1.0
  mongo:
    extends:
      file: common.yml
      service: mongo
