version: '2'
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      # Nginx configuration files
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    ports:
      - "80:80"

networks:
  backend:
    # Use a custom driver which takes special options
    external: 
      name: backend
